
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpperService", targetNamespace = "http://upper/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpperService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toUpperCase", targetNamespace = "http://upper/", className = "client.ToUpperCase")
    @ResponseWrapper(localName = "toUpperCaseResponse", targetNamespace = "http://upper/", className = "client.ToUpperCaseResponse")
    @Action(input = "http://upper/UpperService/toUpperCaseRequest", output = "http://upper/UpperService/toUpperCaseResponse")
    public String toUpperCase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
