/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"


void
prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char result_1;
	char *my_register_1_user_name;
	enum clnt_stat retval_2;
	char result_2;
	char *unregister_1_user_name;
	enum clnt_stat retval_3;
	char result_3;
	char *publish_1_user_name;
	char *publish_1_file_name;
	char *publish_1_file_description;
	enum clnt_stat retval_4;
	char result_4;
	char *my_delete_1_user_name;
	char *my_delete_1_file_name;
	enum clnt_stat retval_5;
	char result_5;
	char *my_connect_1_user_name;
	char *my_connect_1_clientip;
	char *my_connect_1_client_port;
	enum clnt_stat retval_6;
	char result_6;
	char *disconnect_1_user_name;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, PROGVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = my_register_1(my_register_1_user_name, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = unregister_1(unregister_1_user_name, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = publish_1(publish_1_user_name, publish_1_file_name, publish_1_file_description, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = my_delete_1(my_delete_1_user_name, my_delete_1_file_name, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = my_connect_1(my_connect_1_user_name, my_connect_1_clientip, my_connect_1_client_port, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = disconnect_1(disconnect_1_user_name, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_1 (host);
exit (0);
}
