/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_init_database_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (init_database_1_svc(result, rqstp));
}

int
_my_register_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (my_register_1_svc(*argp, result, rqstp));
}

int
_unregister_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (unregister_1_svc(*argp, result, rqstp));
}

int
_publish_1 (publish_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (publish_1_svc(argp->user_name, argp->file_name, argp->file_description, result, rqstp));
}

int
_my_delete_1 (my_delete_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (my_delete_1_svc(argp->user_name, argp->file_name, result, rqstp));
}

int
_my_connect_1 (my_connect_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (my_connect_1_svc(argp->user_name, argp->clientip, argp->client_port, result, rqstp));
}

int
_disconnect_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (disconnect_1_svc(*argp, result, rqstp));
}

int
_list_users_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (list_users_1_svc(*argp, result, rqstp));
}

int
_list_content_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (list_content_1_svc(*argp, result, rqstp));
}

static void
prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *my_register_1_arg;
		char *unregister_1_arg;
		publish_1_argument publish_1_arg;
		my_delete_1_argument my_delete_1_arg;
		my_connect_1_argument my_connect_1_arg;
		char *disconnect_1_arg;
		char *list_users_1_arg;
		char *list_content_1_arg;
	} argument;
	union {
		char my_register_1_res;
		char unregister_1_res;
		char publish_1_res;
		char my_delete_1_res;
		char my_connect_1_res;
		char disconnect_1_res;
		ruser list_users_1_res;
		rcontent list_content_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init_database:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_init_database_1;
		break;

	case my_register:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_my_register_1;
		break;

	case unregister:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_unregister_1;
		break;

	case publish:
		_xdr_argument = (xdrproc_t) xdr_publish_1_argument;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_publish_1;
		break;

	case my_delete:
		_xdr_argument = (xdrproc_t) xdr_my_delete_1_argument;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_my_delete_1;
		break;

	case my_connect:
		_xdr_argument = (xdrproc_t) xdr_my_connect_1_argument;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_my_connect_1;
		break;

	case disconnect:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_disconnect_1;
		break;

	case list_users:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_ruser;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_users_1;
		break;

	case list_content:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_rcontent;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_content_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PROG, PROGVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PROG, PROGVER, prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PROG, PROGVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PROG, PROGVER, prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PROG, PROGVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
